### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by limlynn** [sahilsehwag/android-termux-setup-script#1]
Thank you for sharing this script. 
I could learn a lot from your work.

When I run this script on my phone, I got this error.
Do you know why this is happening?

Thank you.

![Screenshot (Jun 10, 2020 8_45_04 PM)](https://user-images.githubusercontent.com/32457748/84339383-947fd280-ab5b-11ea-8855-d488b685d76b.png)

**Comment by alephalpha0** [comment]
@limlynn it might be something to do with the shebang of the script. `/bin/bash` is not the path to bash in termux. 

This script was made in 2017 and hasn't seen a commit since.. I'm sorry to say there is most likely no use to trying to get it working "as-is".. My bets are that every config option has long since changed and rendered this script obsolete. 

Do yourself a favor and search https://gist.github.com for `termux` and `dot files` for some current starting options.

**Comment by sahilsehwag** [comment]
Hi Sorry for the late reply, Can you tell me the shell you used to execute the script(using `sh ./termux.sh` will not work). I will update the README file to change the shell from `sh` to `bash`.

**Comment by sahilsehwag** [comment]
Hi, I have updated the README file and replaced `sh` with `bash`. I am closing the issue, if you face any issue you can reopen this issue and let me know.
