### ISSUE TITLE
Consider archiving or updating

### ISSUE THREAD

**Issue by alephalpha0** [sahilsehwag/android-termux-setup-script#2]
Hey @sahilsehwag it's been almost 3 years since your last commit. 😘

**Comment by sahilsehwag** [comment]
Hi Sorry for the late reply, The script's working fine. In the original issue I suggested `sh` instead of `bash` to execute the script. But I think I still may have to archive the repository, since many packages are not available in termux mirror repositories. I'll look into it to see if I can add other mirrors or if the missing packages have been renamed.
